### ISSUE TITLE
how compiled

### ISSUE THREAD

**Issue by tefikoff** [ArkerLabs/uniswap-tradingview#1]
how compiled this archive?
I do not see the file index.html
after compilation

**Comment by Nytyr** [comment]
Hello! 
There is no index.html, take a look at the "Usage" section in the readme.

**Comment by tefikoff** [comment]
how added index.html or index.php
<div id="uniswap_tradingview_chart"></div>

**Comment by tefikoff** [comment]
`<div id="uniswap_tradingview_chart"></div>`

**Comment by Nytyr** [comment]
You add this piece of html to you page:

`<div id="uniswap_tradingview_chart"></div>`

Then you execute this in your JS:

```
const chart = new UniswapTradingview({dex: Dex.UNISWAP});
const pairAddress = '0xa478c2975ab1ea89e8196811f51a7b7ade33eb11';
await chart.createChart('uniswap_tradingview_chart', { width: 400, height: 300 }, pairAddress, '1m', 'LINE');
```

**Comment by tefikoff** [comment]
please look
https://delta.webtop.uz/

**Comment by tefikoff** [comment]
http://delta.webtop.uz/screen.png
FTP
